Repository ACM-Thapar/WebDev-Bootcamp, pull requests merged in 2022-10, with the labels that each got.

#1 Add files via upload
  bootcamp/css/docs-home.css
  bootcamp/css/style.css
  bootcamp/docs/docs-home.html
  bootcamp/images/umar-logo.png
  bootcamp/index.html
  bootcamp/js/style.js
  bootcamp/lectures/lecture-home.html
Labels: hacktoberfest, hacktoberfest-accepted

#4 New1
  bootcamp/css/docs-home.css
  bootcamp/css/lec-home.css
  bootcamp/js/style.js
  bootcamp/lectures/lecture-home.html
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#3 Pull request 2
  bootcamp/css/docs-backend.css
  bootcamp/css/docs-frontend.css
  bootcamp/css/docs-home.css
  bootcamp/docs/docs-backend.html
  bootcamp/docs/docs-frontend.html
  bootcamp/images/Html.png
  bootcamp/images/MERN.png
  bootcamp/images/bootstrap.png
  bootcamp/images/css.png
  bootcamp/images/js.svg
  bootcamp/images/node.png
  bootcamp/images/react.png
  bootcamp/images/redux.png
  bootcamp/images/youtube.webp
Labels: hacktoberfest, hacktoberfest-accepted

#5 new files added in lec.
  bootcamp/css/docs-home.css
  bootcamp/css/lec-home.css
  bootcamp/images/video.png
  bootcamp/lectures/bootstrap.html
  bootcamp/lectures/javascript.html
  bootcamp/lectures/lecture-home.html
  bootcamp/lectures/project1.html
  bootcamp/lectures/project2.html
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#10 New3
  README.md
  bootcamp/css/check.css
  bootcamp/css/check.html
  bootcamp/css/docs-home.css
  bootcamp/css/lec-home.css
  bootcamp/css/style.css
  bootcamp/docs/docs-backend.html
  bootcamp/docs/docs-frontend.html
  bootcamp/docs/docs-home.html
  bootcamp/docs/docs-mern.html
  bootcamp/images/Frame1.svg
  bootcamp/images/main.svg
  bootcamp/images/pic1.png
  bootcamp/images/pic1.svg
  bootcamp/images/pic2.png
  bootcamp/images/pic2.svg
  bootcamp/index.html
  bootcamp/js/button.js
  bootcamp/js/style.js
  bootcamp/lectures/bootstrap.html
  bootcamp/lectures/javascript.html
  bootcamp/lectures/node.html
  bootcamp/lectures/project1.html
  bootcamp/lectures/project2.html
  bootcamp/lectures/project3.html
  bootcamp/lectures/react.html
  bootcamp/lectures/redux.html
Labels: hacktoberfest-accepted

#11 New4
  bootcamp/css/docs-others.css
  bootcamp/css/style.css
  bootcamp/images/main.svg
  bootcamp/index.html
Labels: hacktoberfest-accepted
